[package]
name = "tabv"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
csv = "1.3.1"
fs-err = "3.0.0"
glob = "0.3.1"
rapidfuzz = "0.5.0"
ratatui = "0.29.0"
tui-input = "0.11.1"
unicode-width = "0.2.0"
